#### IMPORTANDO LIBRERÍA NUMPY

In [1]:
import numpy as np

##### Creando una lista de 10 Elementos

In [4]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [5]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de objeto


In [6]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [199]:
arreglo.dtype

dtype('int32')

##### Definiendo el Array de int32 a float32


In [8]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [9]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [11]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Obteniendo el promedio del array


In [203]:
promedio = np.mean(arreglo)
promedio

5.5

##### Obteniendo la mediana del array


In [204]:
mediana = np.median(arreglo)
mediana

5.5

##### Desviación Estandar del Arreglo


In [205]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

##### Obtener la dimensión de un arreglo


In [206]:
np.shape(arreglo)


(10,)