#### **IMPORTANDO LIBRERÍA NUMPY**

In [1]:
import numpy as np

##### Creando una lista de 10 Elementos

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [4]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [5]:
arreglo.dtype

dtype('int32')

##### Definiendo el Array de int32 a float32


In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [9]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [10]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [11]:
promedio = np.mean(arreglo)
promedio

5.5

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [12]:
mediana = np.median(arreglo)
mediana

5.5

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [13]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [14]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [15]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [16]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos de Número entre 0 y 1</h4>



In [17]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.33329942, 0.21151185, 0.3238209 , 0.50229858, 0.6976123 ,
       0.47979348, 0.87346985, 0.82695945, 0.83566263, 0.09646163])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [18]:
matriz = np.random.rand(3,3)
matriz

array([[0.44542254, 0.44986286, 0.68677826],
       [0.64327176, 0.44933754, 0.00269496],
       [0.18508971, 0.48216064, 0.29977689]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [19]:
arreglo_aleatorio2  = np.random.randint(1,1001,10)
arreglo_aleatorio2

array([811, 703, 413, 582, 263, 571, 861, 580, 133, 543])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [20]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[ 62,  95,  76,  34,  32,  38,   2,  67,   6,  10],
       [ 57,  14,  49,  63,   2,   6,  49,  50,  37,  68],
       [ 43,  85,  17,  10,  86,  17,  85,  72,  95,  73],
       [ 44,  90,  29,  22,  49,  90,  28,  78,   1,  29],
       [ 30,  58,  58,  30,  89,  42,  52,   3,  71,  56],
       [ 95,  61,  38,   9,  94,  10,  88,  26,  31,  87],
       [ 49, 100,  33,  90,  68,  84,  38,  42,  74,  10],
       [ 23,  42,  79,  76,   8,  23,  51,   6,  28,  34],
       [ 66,  79,  33,  38,  59,  60,  21,  25,  31,  32],
       [ 20,   6,  88,   8,   2,  79,  13,  66,  24,  22]])