#### **IMPORTANDO LIBRERÍA NUMPY**

In [42]:
import numpy as np

##### Creando una lista de 10 Elementos

In [43]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [44]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [45]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [46]:
arreglo.dtype

dtype('int32')

##### Definiendo el Array de int32 a float32


In [47]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [48]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [49]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [50]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [51]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h3 style = "color:cyan"><b>ALGUNAS FUNCIONES DE NUMPY</b></h3>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [52]:
promedio = np.mean(arreglo)
promedio

5.5

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [53]:
mediana = np.median(arreglo)
mediana

5.5

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [54]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [36]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [35]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [37]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos </h4>



In [68]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio 

array([0.51152235, 0.72533798, 0.67604981, 0.98201187, 0.58002376])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [82]:
matriz = np.random.rand(3,3)
matriz

array([[0.81392544, 0.73836766, 0.64052833],
       [0.02843818, 0.48634453, 0.60378751],
       [0.0326113 , 0.58137625, 0.89392101]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [101]:
arreglo_aleatorio2  = np.random.randint(1,5,10)
arreglo_aleatorio2

array([73, 84, 25, 68, 50, 11, 46, 54, 36, 48])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [104]:
matriz2 = np.random.randint(1,100,(15,15))
matriz2

array([[53, 84, 42, 16, 30, 23, 95,  2, 96, 23, 66, 86, 19, 44, 88],
       [19, 30, 86, 21, 71,  8, 82, 12, 78,  1, 46, 28,  1, 56, 80],
       [63, 49, 73, 28, 43, 67, 32, 16, 98, 15, 56, 49, 28, 70, 51],
       [66, 45, 84, 87, 71, 90, 95, 68,  6, 19, 39, 76,  9, 77, 86],
       [13, 34, 33,  3, 29, 35, 85, 37,  5, 74, 56, 82, 87,  9, 72],
       [45, 74, 80, 21, 85, 44, 33, 90, 57,  8, 69, 58, 51, 60, 28],
       [ 2, 34, 79, 91, 76, 26,  3, 76,  8, 79,  1, 70, 86, 30, 44],
       [77, 18,  4, 73, 71, 35, 26, 63, 36, 64, 80, 75, 89,  5, 65],
       [ 6, 85, 55, 88, 54, 71, 55, 92, 87, 17, 36,  2, 71, 88, 37],
       [22, 35, 46, 79, 19, 55, 59, 24, 91, 13, 50, 88, 56, 73, 40],
       [12, 53, 40, 25, 61, 58, 83, 78, 91, 70, 82, 25, 43, 21, 31],
       [72, 48, 49, 52, 42, 49, 98, 63, 37, 42, 11,  7, 23, 74, 77],
       [80, 62,  4, 39, 99, 18,  9, 63, 78, 97, 59, 18, 11, 65, 14],
       [95, 86, 53, 25,  7, 87, 74, 95, 39, 36, 75, 63, 92, 75, 46],
       [66,  5, 98,  7, 74, 74, 80