#### **IMPORTANDO LIBRERÍA NUMPY y RANDOM**

In [24]:
import numpy as np
import random as rd

##### Creando una lista de 10 Elementos

In [25]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [26]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [27]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [28]:
arreglo.dtype

dtype('int32')

##### Definiendo el Array de int32 a float32


In [29]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [30]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [31]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [32]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [33]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [34]:
promedio = np.mean(arreglo)
promedio

5.5

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [35]:
mediana = np.median(arreglo)
mediana

5.5

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [36]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [37]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [38]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [39]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos </h4>



In [40]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio 

array([0.32681211, 0.64141374, 0.937301  , 0.02527993, 0.28729939])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [41]:
matriz = np.random.rand(3,3)
matriz

array([[0.53617813, 0.59914883, 0.11541722],
       [0.27471051, 0.99748363, 0.71464138],
       [0.1436161 , 0.24229644, 0.35554839]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [42]:
arreglo_aleatorio2  = np.random.randint(1,5,10)
arreglo_aleatorio2

array([2, 4, 2, 2, 4, 4, 1, 3, 3, 2])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [43]:
matriz2 = np.random.randint(1,100,(15,15))
matriz2

array([[97, 90, 41,  2,  2, 75, 88, 43, 98, 23, 60, 63, 95, 81,  6],
       [28, 95, 60, 36, 26, 64, 34, 37, 16, 52, 35, 81, 26, 83, 59],
       [75, 13, 32, 24, 61, 91,  4, 11, 52, 98, 53, 25, 90,  3, 14],
       [89, 92, 42, 14, 56, 44, 90, 71, 76,  9, 67, 54, 75, 31, 98],
       [34, 45, 20, 79, 57, 24, 55, 55, 86,  5, 25, 85, 20, 60, 47],
       [68, 19, 40, 32, 12,  4, 90, 98, 23, 67,  9, 13, 62, 85, 26],
       [ 3, 68, 39, 65, 21, 90,  3, 63, 34, 44, 30, 72, 48, 90, 24],
       [75,  1, 41, 43, 25,  3, 77, 62,  3, 92,  4, 79, 99, 38,  2],
       [84, 52, 35, 18, 67, 87, 87, 98, 76, 38, 57,  4, 70, 70, 88],
       [78, 84, 95, 62, 18, 77, 70, 28, 75, 36, 58, 30,  3, 16,  1],
       [85, 97, 42, 56, 14, 97, 53, 98, 79, 63, 18, 34, 70, 15, 32],
       [93, 18, 83, 95, 12,  8, 37, 31, 20, 28, 22, 96, 88, 94, 28],
       [14, 28, 89, 26, 57, 39, 69, 62, 79, 56, 66,  7, 27, 37, 67],
       [89, 34, 58,  6, 52, 62, 70, 42, 50, 25, 91, 86, 48, 18, 47],
       [60, 85, 65, 65, 97,  7, 40