#### **IMPORTANDO LIBRERÍA NUMPY y RANDOM**

In [2]:
import numpy as np
import random as rd

##### Creando una lista de 10 Elementos

In [3]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [4]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [5]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [6]:
arreglo.dtype

dtype('int32')

##### Definiendo el Array de int32 a float32


In [7]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [8]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [9]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [10]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [11]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [12]:
promedio = np.mean(arreglo)
promedio

5.5

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [13]:
mediana = np.median(arreglo)
mediana

5.5

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [14]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [24]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [25]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [17]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos </h4>



In [151]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.1989271 , 0.18713664, 0.25147033, 0.60860052, 0.20576783,
       0.03344157, 0.59695651, 0.24404677, 0.83773651, 0.34949799])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [126]:
matriz = np.random.rand(3,3)
matriz

array([[0.20450182, 0.08153636, 0.66412584],
       [0.59039027, 0.20453019, 0.75452114],
       [0.18271082, 0.38853793, 0.80691522]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [112]:
arreglo_aleatorio2  = np.random.randint(1,1001,5)
arreglo_aleatorio2

array([829, 726, 257,  54, 336])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [156]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[ 82,  63,   8,  68,  83,  60,  80,  16,  78,  85],
       [ 63,  97,  53,  45,  41,  36,  12,  30,  31,  16],
       [ 25,  41,  96,  58,  84,  26,  33,  42,  65,  40],
       [ 91,  72,  50,   3,  87,  63,  40,  88,  44,  76],
       [  9,  10,  73,  73,  59,  98,  14,   9,  19,  32],
       [ 36,  11,  34,   9,  69,  36,  98,  79,  39,  16],
       [ 45,  51,  45,  32,  69,  12,  57,  44,  68,  11],
       [ 85,  97,  60,  50,  80,   2,  65,   9,  56,  11],
       [  9,  60,  96,  29,  80,  82,  12,  64,   8,  23],
       [  5,  85,  39,  75,   3, 100,  27,  56,  45,   1]])