<h3 style = "color:yellow">DIMENSIONES</h4>


In [21]:
import numpy as np

<h4 style = "color:orange"> Generando un Array de 9 elementos con Random </h4>

In [22]:
arreglo = np.random.randint(1,10,12)
arreglo

array([6, 5, 4, 6, 2, 7, 5, 1, 2, 9, 3, 6])

<h4 style = "color:orange"> Obtener la dimensión de una arreglo </h4>

In [23]:
np.shape(arreglo)

(12,)

<h4 style = "color:orange"> Transformación del vector de 9 elementos a Matriz 4x3 con Reshape </h4>


In [24]:
matriz = arreglo.reshape(4,3)
matriz

array([[6, 5, 4],
       [6, 2, 7],
       [5, 1, 2],
       [9, 3, 6]])

<h4 style = "color:orange"> Otra Transformación del vector de 9 elementos a Matriz 3x4 con Reshape </h4>


In [25]:
matriz = arreglo.reshape(3,4)
matriz

array([[6, 5, 4, 6],
       [2, 7, 5, 1],
       [2, 9, 3, 6]])