<h2 style="color:#00ade4;font-family:Arial">DIMENSIONES</h2>


In [6]:
import numpy as np

<h4 style = "color:cyan"> Generando un Array de 9 elementos con Random </h4>

<image src="assets/img/Vectorv1.png" width=20% alt="Descripción de la imagen">


In [7]:
arreglo = np.random.randint(1,10,12)
arreglo

array([3, 2, 4, 1, 3, 3, 6, 5, 3, 7, 2, 5])

<h4 style = "color:cyan"> Obtener la dimensión de un arreglo </h4>

In [8]:
np.shape(arreglo)

(12,)

<h4 style = "color:cyan"> Transformación del vector de 9 elementos a Matriz 4x3 con Reshape </h4>


<image src="assets/img/matrix.png" width=15% alt="Descripción de la imagen">


In [9]:
matriz = arreglo.reshape(4,3)
matriz

array([[3, 2, 4],
       [1, 3, 3],
       [6, 5, 3],
       [7, 2, 5]])

<h4 style = "color:cyan"> Otra Transformación del vector de 9 elementos a Matriz 3x4 con Reshape </h4>


In [10]:
matriz = arreglo.reshape(3,4)
matriz

array([[3, 2, 4, 1],
       [3, 3, 6, 5],
       [3, 7, 2, 5]])

<h4 style = "color:cyan"> Creando un Tensor </h4>

<image src="assets/img/tensor.png" width=20% alt="Descripción de la imagen">
